[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
optimizer_runs = 1_000_000

[fmt]
line_length = 100
number_underscore = "thousands"

[rpc_endpoints]
optimism = "${ARCHIVE_NODE_URL_L2}"
optimismGoerli = "${ARCHIVE_NODE_URL_GOERLI_L2}"

[etherscan]
optimism = { key = "${ETHERSCAN_API_KEY}" }
optimismGoerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
